baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Teaching'
pageRef = '/teaching'
url = '#teaching'
weight = 10

[[menus.main]]
name = 'Publications'
pageRef = '/publications'
url = '#publications'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"